services:
  postgres:
    image: paradedb/paradedb:latest
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
    environment:
      POSTGRES_USER: genai_super
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
      PGPORT: 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U genai_super -d mydb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    # This container uses the ParadeDB image with roles and extensions initialized via db_init.sql

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "3000:80"
    depends_on:
      postgres:
        condition: service_healthy